use_frameworks!

platform :ios, '15.0'

install! 'cocoapods', :deterministic_uuids => false

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
end

pod 'GoogleSignIn'
pod 'FirebaseCore'
pod 'FirebaseAuth'
pod 'FirebaseAnalytics'
