target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
end

pod 'GoogleSignIn', '7.0.0'
pod 'FirebaseCore', '10.15.0'
pod 'FirebaseAuth', '10.15.0'
pod 'FirebaseAnalytics', '10.15.0'
