name: AppStore version create

on:
    push:
        branches:
            - app_store_version_create

jobs:
    app_store_version_create:
        runs-on: macos-12
        steps:
            -   name: Install private API key P8
                env:
                    PRIVATE_API_KEY_BASE64: ${{ secrets.MIXDRINKS_IOS_APPSTORE_API_PRIVATE_KEY }}
                    API_KEY: ${{ secrets.MIXDRINKS_IOS_APPSTORE_API_KEY_ID }}
                run: |
                    mkdir -p ~/private_keys
                    echo -n "$PRIVATE_API_KEY_BASE64" | base64 --decode --output ~/private_keys/AuthKey_$API_KEY.p8

            -   name: Get token
                id: asc
                uses: yuki0n0/action-appstoreconnect-token@v1.0
                with:
                    issuer id: ${{ secrets.MIXDRINKS_IOS_APPSTORE_ISSUER_ID  }}
                    key id: ${{ secrets.MIXDRINKS_IOS_APPSTORE_API_KEY_ID }}
                    key: ${{ secrets.MIXDRINKS_IOS_APPSTORE_API_PRIVATE_KEY }}

            -   name: Use token
                run: |
                    JSON=`curl -sS -H "Authorization:Bearer ${{ steps.asc.outputs.token }}" https://api.appstoreconnect.apple.com/v1/apps`
