name: Publish ios build

on:
  push:
    branches:
      - prepare_ios_ci

jobs:
  deploy_ios:
    env:
      MIXDRINKS_MOBILE_APP_VERSION_NAME: "1.2.0"
      MIXDRINKS_MOBILE_APP_VERSION_CODE: 10
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build xcworkspace
        run: ./gradlew podInstall

      - uses: sparkfabrik/ios-build-action@v2.1.0
        with:
          upload-to-testflight: true
          increment-build-number: false
          build-pods: false
          pods-path: "iosApp/Podfile"
          export-method: ad-hoc
          workspace-path: "iosApp/iosApp.xcworkspace"
          project-path: "iosApp/iosApp.xcodeproj"
          scheme: iosApp
          output-path: build-test.ipa
          apple-key-id: ${{ secrets.MIXDRINKS_IOS_APPSTORE_API_KEY_ID }}
          apple-key-issuer-id: ${{ secrets.MIXDRINKS_IOS_APPSTORE_ISSUER_ID }}
          apple-key-content: ${{ secrets.MIXDRINKS_IOS_APPSTORE_API_PRIVATE_KEY }}
          team-id: "9LJW42P73L"
          team-name: "Volodymyr Stelmashchuk"
          ios-app-id: org.mixdrinks.app9LJW42P73L
