name: Run Gradle on PRs
on: pull_request

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, self-hosted-person-mac-book-pro ]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: gradle shared:check
