name: Run Gradle on PRs
on: pull_request

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, self-hosted ]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: amyu/setup-android@v2

      - run: ./gradlew check