name: Run Gradle on PRs
on: pull_request

jobs:
    tests:
        strategy:
            matrix:
                os: [ ubuntu-22.04 ]
        runs-on: ${{ matrix.os }}
        continue-on-error: true
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 11 for x64
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'adopt'
                    architecture: x64
            -   name: Build with Gradle
                uses: gradle/gradle-build-action@v2.5.1
                with:
                    arguments: check
